#cloud-config
packages_update: true
packages_upgrade: true

yum_repos:
    epel-testing:
        baseurl: https://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/$basearch/
        enabled: true
        failovermethod: priority
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
        name: EPEL ($basearch)

packages:
  - git
  - lzop
  - gcc
  - gcc-c++
  - make
  - libpq
  - postgresql-server-devel
  - postgresql
  - postgresql-server

runcmd:
  - [wget, https://raw.githubusercontent.com/canha/golang-tools-install-script/master/goinstall.sh, -P, /tmp]
  - [sudo, su, opc, -c, "sh /tmp/goinstall.sh"]
  - [sudo, postgresql-setup, --initdb]
  - [systemctl, enable, postgresql.service]
  - [sudo, systemctl, start, postgresql.service]
  - [sudo, firewall-offline-cmd, --zone=public, --add-port=80/tcp]
  - [sudo, firewall-offline-cmd, --zone=public, --add-port=5432/tcp]
  - [systemctl, restart, firewalld]